# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cutIntervals <- function(x1, x2, y1, y2) {
    .Call(`_ibts_cutIntervals`, x1, x2, y1, y2)
}

findI_et <- function(x, y1, y2) {
    .Call(`_ibts_findI_et`, x, y1, y2)
}

findI_st <- function(x, y1, y2) {
    .Call(`_ibts_findI_st`, x, y1, y2)
}

mwIndices <- function(win_half, delta_t, x) {
    .Call(`_ibts_mwIndices`, win_half, delta_t, x)
}

